pipeline {
    
    agent any
    environment{
        DOCKERHUB_USER = "mahmudulrm"
        APP_NAME = "gitops-argo-app"
        IMAGE_TAG = "${BUILD_NUMBER}"
        IMAGE_NAME = "${DOCKERHUB_USER}" + "/" + "${APP_NAME}"
        REGISTRY_CREDS = 'dockerhub'
        // add - manage jenkins > credentials > system > global credentials - add credentials
        // git hub access personal token
    }
    stages{
        stage('clean workspace'){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        stage("checkout SCM"){
            steps{
                script{
                //Need to add jenkins credentialsId - github - git user and git personal token
                    git credentialsId: 'github', url: 'https://github.com/mahmudulrm/gitops-jenkins-argocd.git', branch: 'main'
                }
            }
        }
		//plugins for docker (docker pipline, dashboard view) 
        stage("Docker build Image"){
            steps{
                script{
                    docker_image = docker.build "${IMAGE_NAME}"
                }
            }
        }
		// install docker on jenkins server
        stage("Docker push Image"){
            steps{
                script{
                    docker.withRegistry('', REGISTRY_CREDS){
                        docker_image.push("$BUILD_NUMBER")
                        docker_image.push('latest')
                    }
                }
            }
        }
        stage("Docker Image remove"){
            steps{
                script{
                    sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG}"
                    sh "docker rmi ${IMAGE_NAME}:latest"
                }
            }
        }
        stage("trigger config change pipeline"){
            steps{
                script{
                    sh "curl -v -k -u mahmudul:111841aa6f3183fde3b5e4767c17d52519 -H 'cache-control: no-cache' -H 'content-type: application/x-www-form-urlencoded' 'http://172.0.30.54:8080/job/gitops-argocd_CD/buildWithParameters?token=gitops-config' --data 'IMAGE_TAG=${IMAGE_TAG}' --data cause='Tigger by CI pipline'"
                }
            }
        }
    }              
}
